/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cadastro;

import app.InterfacePainel;
import dao.PedidoDao;
import dao.ProdutoDao;
import dto.CarrinhoDTO;
import dto.InterfaceDTO;
import implementsDao.PedidoImplementsDAO;
import implementsDao.ProdutoImplementsDAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Pedido;
import model.Produto;

/**
 *
 * @author alenc
 */
public class PainelCarrinho extends InterfacePainel {

    /**
     * Creates new form PainelCarrinho
     */
    private final PedidoDao pedDao = new PedidoImplementsDAO();
    private final ProdutoDao prodDao = new ProdutoImplementsDAO();
    private List<Pedido> listaPed;
    private List<Produto> listaProd;
    CarrinhoDTO dto;

    public PainelCarrinho() {
        initComponents();
        carregarComboPedido();
        carregarComboProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBoxPedido = new javax.swing.JComboBox<>();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quantidade de itens");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedido");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Produto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jComboBoxPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxPedido;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void carregarComboPedido() {
        try {
            listaPed = pedDao.listar();
            jComboBoxPedido.removeAllItems();
            jComboBoxPedido.addItem("— Selecione —");
            for (Pedido p : listaPed) {
                jComboBoxPedido.addItem(String.valueOf(p.getNumeroPedido()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar pedido: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void carregarComboProduto() {
        try {
            listaProd = prodDao.listar();
            jComboBoxProduto.removeAllItems();
            jComboBoxProduto.addItem("— Selecione —");
            for (Produto pro : listaProd) {
                jComboBoxProduto.addItem(pro.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar produto: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public InterfaceDTO getDados() {
        if ( dto == null) {
            dto = new CarrinhoDTO();
        }
        
        dto.qntdItens = jTextField1.getText().trim();
        
        int indexP = jComboBoxPedido.getSelectedIndex();
        if (indexP >= 0 && indexP < listaPed.size()) {
            int realIndexP = indexP - 1;
            
            dto.idPedido = String.valueOf(listaPed.get(realIndexP).getId());
        } else {
            dto.idPedido = null;
        }
        
        int indexPro = jComboBoxProduto.getSelectedIndex();
        if (indexPro >= 0 && indexPro < listaProd.size()) {
            int realIndexPro = indexP - 1;
            
            dto.idProduto = String.valueOf(listaProd.get(realIndexPro).getId());
        } else {
            dto.idProduto = null;
        }
        
        return (InterfaceDTO) dto;
    }

    @Override
    public void setDados(InterfaceDTO dto) {
        this.dto = (CarrinhoDTO) dto;
        
        jTextField1.setText(this.dto.qntdItens);
        
       if (this.dto.idPedido != null && listaPed != null) {
            int idP = Integer.parseInt(this.dto.idPedido);
            
            for (int i = 0; i < listaPed.size(); i++) {
                if (listaPed.get(i).getId() == idP) {
                    jComboBoxPedido.setSelectedIndex(i + 1);
                    break;
                }
            }
        } else {
           jComboBoxPedido.setSelectedIndex(0);
       }
       
       if (this.dto.idProduto != null && listaProd != null) {
            int idP = Integer.parseInt(this.dto.idProduto);
            
            for (int i = 0; i < listaProd.size(); i++) {
                if (listaProd.get(i).getId() == idP) {
                    jComboBoxProduto.setSelectedIndex(i + 1);
                    break;
                }
            }
        } else {
           jComboBoxProduto.setSelectedIndex(0);
       }
    }
}
