/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package cadastro;

import app.InterfacePainel;
import dao.PedidoDao;
import dto.InterfaceDTO;
import dto.ReembolsoDTO;
import implementsDao.PedidoImplementsDAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Pedido;

/**
 *
 * @author alenc
 */
public class PainelReembolso extends InterfacePainel {

    /**
     * Creates new form PainelReembolso
     */
    private final PedidoDao pedidoDao = new PedidoImplementsDAO();
    private List<Pedido> listaPedido;
    ReembolsoDTO dto;

    public PainelReembolso() {
        initComponents();
        carregarComboPedido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Motivo");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pedido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void carregarComboPedido() {
        try {
            listaPedido = pedidoDao.listar();
            jComboBox1.removeAllItems();
            jComboBox1.addItem("Selecione");
            for (Pedido p : listaPedido) {
                jComboBox1.addItem(String.valueOf(p.getNumeroPedido()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar pedido: " + e.getMessage());
        }
    }

    @Override
    public InterfaceDTO getDados() {
        if (dto == null) {
            dto = new ReembolsoDTO();
        }

        dto.motivoReemb = jTextField1.getText();

        int indiceP = jComboBox1.getSelectedIndex();
        if (indiceP > 0 && indiceP <= listaPedido.size()) {
            Pedido escolhido = listaPedido.get(indiceP -1);
            dto.idPedidoR = String.valueOf(escolhido.getId());
        } else {
            dto.idPedidoR = null;
        }

        return dto;
    }

    @Override
    public void setDados(InterfaceDTO dto) {
        if (dto != null) {
            this.dto = (ReembolsoDTO) dto;
            jTextField1.setText(this.dto.motivoReemb);
        } else {
            this.dto = new ReembolsoDTO();
            jTextField1.setText("");
        }

        if (listaPedido != null && !listaPedido.isEmpty() && this.dto.idPedidoR != null) {
            int idP = Integer.parseInt(this.dto.idPedidoR);
            for (int i = 0; i < listaPedido.size(); i++) {
                if (listaPedido.get(i).getId() == idP) {
                    jComboBox1.setSelectedIndex(i + 1);
                    return;
                }
            }
        }
        jComboBox1.setSelectedIndex(0);
    }
}
